dappnode/DAppNode

team.md
Updated the team info for all current contributors
=> Created a new team.md

roadmap.md
This roadmap details development for the next 6 months.
=> Created roadmap

Dockerfile, iso/scripts/generate_dappnode_iso_debian.sh
- Update ISO image
- Verify download with shasum 256
=> Update ISO image and verify download with shasum

.dappnode_profile, Dockerfile, iso/scripts/generate_dappnode_iso_debian.sh, scripts/dappnode_access_credentials.sh, scripts/dappnode_install.sh
- Update debian ISO image
- Verify shasum debian iso image
- Added welcome message
- Added `dappnode_help` command
- Renamed `dappnode_connect` to `dappnode_openvpn`
- Typed errors of commands `dappnode_wireguard` and `dappnode_openvpn`  if containers do not exist
- Removed execution of `dappnode_access_credentials.sh` script on startup
- Execution of `dappnode_access_credentials.sh` script on demmand with command `dappnode_connect`
=> commands refactor && update debian ISO image

iso/preseeds/preseed.cfg, iso/preseeds/preseed_unattended.cfg, scripts/dappnode_install_pre.sh
- Add iptables package to preseeds
- Add iptables to preinstall script
=> Add iptables package

scripts/dappnode_install_pre.sh
- Added comments
- Fix typo in iptables check
=> Improve preinstall script

scripts/dappnode_install.sh
Append welcome message to motd on dappnode installer instead of executing it from profile
=> Append welcome message to motd

.github/workflows/linter.yml
=> fix linter

.github/workflows/linter.yml, .github/workflows/release.yml
New releases require manually setting the new core versions to be used by the profile. The profile must be changed once the `relase` workflow has completed successfully
=> update profile on new releases

.github/workflows/release.yml
Ignore empty lines and spaces in `git diff` for automated PRs
=> Ignore empty lines and spaces in `git diff`

iso/scripts/download_core.sh, scripts/dappnode_install.sh
Remove openethereum hash from the installer
=> Deprecate openethereum

README.md
still need to update graphics but the important links are updated.
=> update outdated links

iso/scripts/generate_dappnode_iso_debian.sh
Fix outdated link to Debian 11.5
=> Update outdated link to Debian ISO

docker-compose.yml
revert personal changes 
This is/was a personal test branch and i have been testing it offline and saved my local work on my branch and pushed it and then when went back to github i found that @dappnode/core had started to move on it themselves so my last commit from my VS-Code wasnt made as a PR because I didnt know anyone was planning on implmenting it just yet for everyone especially
=> revert Update docker-compose.yml

iso/scripts/generate_dappnode_iso_debian.sh
=> update debian iso

iso/scripts/generate_dappnode_iso_debian.sh
Update base Debian version to 12.4.0
=> Update Debian version to 12.4.0

funding.json
adding a temporary JSON to verify the repository in Optimism's RPGF5
=> Verification for RPGF5

.github/workflows/test.yml
Use docker compose binary in test ci
=> Use docker compose binary in test ci

iso/scripts/generate_dappnode_iso_debian.sh
Bump debian image from 12.7.0 to 12.8.0
=> Bump debian image to 12.8.0

iso/scripts/generate_dappnode_iso_debian.sh
=> Bump bookworm to 12.9.0

iso/scripts/generate_dappnode_iso_debian.sh
=> bump bookworm 12.10.0

.dappnode_profile
add docker compose down for core packages. It does not remove named volumes
=> add docker compose down for core pkg
