dappnode/DAppNode

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/contributing.rst
docs/frequently-asked-questions.rst

Riot has recently been rebranded to Element. This pull request and those like it on the other repositories update the branding and room address to reflect this.

Update README (Riot to Element Rebranding)

---

scripts/dappnode-core-update.sh

**Script**
This script has as main goal to automate the process of getting a core package updated at the time of a new release testing.
It asks you which core packages will be updated in the new relase, and which branch of each of them. Then it will generate the IPFS HASH for each one, edit the manifest of the DNP_CORE and get the IPFS of the DNP_CORE with the dependencies updated.
**Result**
In this case only the ipfs of the VPN package was selected.
**Requirements**
- jq
- more utils (linux)
- dappnodeSDK installed globally
- GIT installed globally

Added script to automate the core update

---

scripts/dappnode-iso-image.sh

**Automate ISO creation**
Usually needed when a new realese needs to be tested. 
INPUT -> which core packages will be updated and their tags. 
OUTPUT -> ISO image based on the core packages versions (including the new ones)
**Future improvemnts**
Would be a good idea to execute this script maybe inside a remote server and install it there
RESULTS
**.dappnode_profile** edited deppending on the input
**script execution**
**ISO image as output**

added script to create iso image

---

.github/workflows/release.yml

CI to create pre-release on demmand
Requirements:
- Core packages release must exist and marked as "release" instead of pre-release
- Set all core packages versions of the new release
- Set new core version with 'v'

New CI to create pre-release

---

iso/scripts/generate_dappnode_iso_debian.sh

fix hardcoded link to firmware-11.1.0-amd64-netinst.iso, also due to incomplete ssl certificate on FTP archive server this must be done HTTP not HTTPS, but the hash checking should resolve it
Fixes #381 
should merge this so the ISO scripts work again then explore the v11.2.0 firmware for security upgrades

Fix hardcoded link to firmware-11.1.0-amd64-netinst.iso

---

iso/scripts/generate_ISO.sh
iso/scripts/generate_dappnode_iso_debian.sh

Clean ISO image when var CLEAN is set to true in order to avoid cache created. This may affect creating an unattended image right after the attended

clean DAppNode iso image when CLEAN=true

---

README.md
iso/preseeds/preseed.cfg
iso/preseeds/preseed_unattended.cfg
iso/scripts/generate_dappnode_iso_debian.sh
scripts/dappnode_install_pre.sh

- Deleting old way of installing docker and adding docker repo to the install
- Dropping support for old Debian versions

Move Docker install to Docker repo

---

iso/preseeds/preseed_unattended.cfg

Disabling password for root user should make add first user to sudoers.
Test instructions:
- Install DAppNode ISO to fresh machine
- `sudo <command>` should work, i.e. ask for user password

Disabled root password and adding dappnode user to sudo

---

iso/scripts/generate_dappnode_iso_debian.sh

Updated Debian version. This fixes the problem that some NUC 11s come with a different network chipset (i225-V instead of i225-LM), which causes the network card not to be detected.

Updated Debian version

---

iso/scripts/generate_dappnode_iso_debian.sh

workflows (and builds) fail now because this script pulls from the current version released of non free bullseye firmware ISOs.  11.5 is no longer current, 11.6 has supplanted it.  Updated the script target to the new home of the 11.5 non-free ISO in the archive.

update debian download link to archive permalink

---

README.md

There was a capitalization error in the instructions that causes the command to run incorrectly

fix: ls path incorrect

---

scripts/dappnode_install.sh

adds lodestar to content hashes in the installer
Lodestar mainnet must be published before this can be merged.

Add Lodestar to content hash installer

---

iso/preseeds/preseed_unattended.cfg

For unattended installs, it makes sense the most that we set clock to UTC timezone.

Update preseed_unattended.cfg time to UTC

---

scripts/dappnode_install.sh

A missing `openvt` can make the script fail and lead to data loss.

installer: Install kbd package

---

.dappnode_profile

Add the `docker-compose` command as an alias. In newer docker versions, docker-compose has been deprecated.
Only add the alias if docker compose does not throw an error

Alias for compose backwards compatibility

---

.github/workflows/artifacts.yml
.github/workflows/linter.yml
.github/workflows/release.yml
.github/workflows/test.yml

Workflows use actions that were out of date. This PR updates them

Update actions versions

---

.dappnode_profile

Add comments to version definition

Add comments to version definition

---

.github/workflows/artifacts.yml
.github/workflows/release.yml
Dockerfile
iso/scripts/generate_dappnode_iso_debian.sh
scripts/dappnode_install_pre.sh

Use new docker compose  instead of legacy docker-compose binary

Use new docker compose 

---

README.md

While checking the document I figure out that the link to Installation guideline becomes invalid. It is updated with a correct link now.

Fix invalid link to Installation guideline in README.md

---

scripts/dappnode_install_pre.sh

Remove check connectivity test for prerequisite script
